version: "3.8"
services:
  example:
    build:
      target: base
    volumes:
      - "./example/src:/app/src:ro"
    command: yarn dev
 auth:
    build:
      target: base
    volumes:
      - "./auth/src:/app/src:ro"
    command: yarn dev