version: '3.8'
services:
  nginx:
    image: 'nginx:1.21.1-alpine'
    container_name: nginx
    hostname: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/nginx.conf:ro'
    restart: always

  auth:
    build:
      context: ./services/auth
      target: production
    container_name: auth
    hostname: auth
    restart: always
    command: 'yarn start'

  stranerd:
    build:
      context: ./services/stranerd
      target: production
    container_name: stranerd
    hostname: stranerd
    restart: always
    command: 'yarn start'

  utils:
    build:
      context: ./services/utils
      target: production
    container_name: utils
    hostname: tasks
    restart: always
    command: 'yarn start'