version: '3.8'
services:
  traefik:
    build:
      context: ./docker/traefik
      args:
        BASE_DOMAIN: ${BASE_DOMAIN}
        USE_SSL: ${USE_SSL}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/data/docker/mstranerd/traefik/acmeStaging.json:/etc/traefik/acmeStaging.json"
      - "/data/docker/mstranerd/traefik/acmeProduction.json:/etc/traefik/acmeProduction.json"
      - "/data/docker/mstranerd/traefik/log.json:/etc/traefik/log.json"
      - "/data/docker/mstranerd/traefik/accessLog.json:/etc/traefik/accessLog.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  auth:
    build:
      context: ./services/auth
      target: production
    hostname: auth
    restart: always
    volumes:
      - '/data/docker/mstranerd/files/auth/:/app/public/'
    command: 'yarn start'

  stranerd:
    build:
      context: ./services/stranerd
      target: production
    hostname: stranerd
    restart: always
    volumes:
      - '/data/docker/mstranerd/files/stranerd/:/app/public/'
    command: 'yarn start'

  utils:
    build:
      context: ./services/utils
      target: production
    hostname: tasks
    restart: always
    volumes:
      - '/data/docker/mstranerd/files/utils/:/app/public/'
    command: 'yarn start'