version: "3.8"
services:
  auth:
    build:
      target: base
    volumes:
      - "./services/auth/src:/app/src:ro"
    command: "sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn dev"

  stranerd:
    build:
      target: base
    volumes:
      - "./services/stranerd/src:/app/src:ro"
    command: "sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn dev"

  utils:
    build:
      target: base
    volumes:
      - "./services/utils/src:/app/src:ro"
    command: "sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn dev"