version: '3.8'
services:
  traefik:
    build:
      context: ./docker/traefik
      args:
        BASE_DOMAIN: ${BASE_DOMAIN}
        USE_SSL: ${USE_SSL}
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/traefik/certs/:/ssl-certs/"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  auth:
    build:
      context: ./services/auth
      target: production
    container_name: auth
    hostname: auth
    restart: always
    command: 'yarn start'

  stranerd:
    build:
      context: ./services/stranerd
      target: production
    container_name: stranerd
    hostname: stranerd
    restart: always
    command: 'yarn start'

  utils:
    build:
      context: ./services/utils
      target: production
    container_name: utils
    hostname: tasks
    restart: always
    command: 'yarn start'