version: "3.8"
services:
  example:
    build:
      target: base
    volumes:
      - "./example/src:/app/src:ro"
<<<<<<< HEAD
    command: yarn dev
 auth:
    build:
      target: base
    volumes:
      - "./auth/src:/app/src:ro"
    command: yarn dev
=======
    command: sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn dev
>>>>>>> d513bec9715e2b0eea30b34864cca46e8292ee8a
