version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  example:
    build:
      context: ./example
      target: production
    environment:
      - PORT=5000
    restart: unless-stopped
    depends_on:
      - mongo
    command: yarn start

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    restart: unless-stopped

  rabbitmq:
    build:
      context: ./rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-db:
