version: "3.8"
services:
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped

  auth:
    build:
      context: ./auth
      target: production
    restart: unless-stopped
    depends_on:
      - mongodb
    command: sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn start

  emails:
    build:
      context: ./emails
      target: production
    restart: unless-stopped
    depends_on:
      - mongodb
    command: sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn start

  example:
    build:
      context: ./example
      target: production
    restart: unless-stopped
    depends_on:
      - mongodb
    command: sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn start

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "mongo-db:/data/db"
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    build:
      context: ./rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"

  redis:
    image: redis:6.2.5-alpine

volumes:
  mongo-db: