version: "3.8"
services:
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped
    depends_on:
      - example

  example:
    build:
      context: ./example
      target: production
    restart: unless-stopped
    ports:
      - "3000:5000"
    depends_on:
      - mongodb
    command: yarn start

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "mongo-db:/data/db"
    restart: unless-stopped
    ports:
      - "27017:27017"
    depends_on:
      - rabbitmq

  rabbitmq:
    build:
      context: ./rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.5-alpine

volumes:
  mongo-db:
