runtime: nodejs16
service: stranerd

instance_class: B2

env_variables:
  PORT: 8080

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

manual_scaling:
  instances: 1