name: Publish to GCloud App Engine

on:
  push:
    branches:
      staging

jobs:
  publish-gae:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Fetch secrets
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
        with:
          args: secrets versions access latest --secret=Micro_Stranerd_Environment_Variables > env.json
      - name: Create .env Files
        run: make copy-envs
      - name: Set Apps In Environment Variables
        run: echo "APPS=$(make echo-apps)" >> $GITHUB_ENV
      - name: Install Dependencies
        run: make install-all
      - name: Build Apps
        run: make build-all
      - name: Deploy to GAE
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
        with:
          args: app deploy ${{ env.APPS }} --quiet